#!/usr/bin/env bash
# prints the message infinity and beyon for 
# eternity unless killed
echo $$ > /var/run/myscript.pid

close()
{
  echo "$1"
  return
}

delete_file()
{
  if [ -e "/var/run/myscript.pid" ]
  then
    rm /var/run/myscript.pid
  fi
}
# SIGTERM
trap "close 'I hate the kill command' && delete_file && exit" SIGTERM

# SIGINT
trap "close 'Y U no love me?!' && exit"  SIGINT

# SIGQUIT
trap "delete_file && exit" SIGQUIT

while true;
do
  echo "To infinity and beyond";
  sleep 2
done
