#!/usr/bin/env bash
# displays information about the School file

file="school"

if [ -e $file ]
then
    echo "School file exists"
    if [ -s $file ]
    then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi
    if [ -f $file ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
